import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

interface ShopInfo {
    name: string;
    location: string;
    contact: string;
    serialNumber?: string;
}

interface UserInfo {
    name: string;
    email?: string;
}

interface StockItem {
    productCode: string;
    name: string;
    price: number;
    qty: number;
}

export const generateRestockPDF = (
    stocks: StockItem[],
    shopInfo: ShopInfo,
    userInfo: UserInfo,
    isHp: boolean
) => {
    const doc = new jsPDF();
    const timestamp = format(new Date(), 'dd/MM/yyyy HH:mm:ss');
    const typeLabel = isHp ? 'Half Price (HP) Stock' : 'Regular Stock';

    // Banner / Header
    doc.setFillColor(34, 197, 94); // Green-600 (Primary-ish)
    doc.rect(0, 0, 210, 40, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text(shopInfo.name || 'TIENS SHOP', 15, 15);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Location: ${shopInfo.location || 'N/A'}`, 15, 22);
    doc.text(`Contact: ${shopInfo.contact || 'N/A'}`, 15, 27);
    doc.text(`Serial: ${shopInfo.serialNumber || 'N/A'}`, 15, 32);

    doc.setFontSize(16);
    doc.text('OUT OF STOCK REPORT', 140, 15);
    doc.setFontSize(10);
    doc.text(`Type: ${typeLabel}`, 140, 22);
    doc.text(`Date: ${timestamp}`, 140, 27);

    // Metadata Section
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Report Details', 15, 50);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated by: ${userInfo.name}`, 15, 57);
    doc.text(`Total Items Needing Restock: ${stocks.length}`, 15, 62);

    // Table
    autoTable(doc, {
        startY: 70,
        head: [['Code', 'Product Name', 'Unit Price (UGX)', 'Current Qty']],
        body: stocks.map(item => [
            item.productCode,
            item.name,
            item.price.toLocaleString(),
            item.qty.toString()
        ]),
        headStyles: {
            fillColor: [34, 197, 94],
            textColor: [255, 255, 255],
            fontSize: 10,
            fontStyle: 'bold',
            halign: 'center'
        },
        columnStyles: {
            0: { cellWidth: 30, fontStyle: 'bold' },
            1: { cellWidth: 'auto' },
            2: { cellWidth: 40, halign: 'right' },
            3: { cellWidth: 30, halign: 'center' }
        },
        styles: {
            fontSize: 9,
            cellPadding: 3
        },
        alternateRowStyles: {
            fillColor: [240, 253, 244] // Very light green
        },
        margin: { top: 70 }
    });

    // Footer
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(
            `TIENS POS System - Generated for ${shopInfo.name} - Page ${i} of ${pageCount}`,
            15,
            285
        );
    }

    doc.save(`restock_report_${isHp ? 'hp' : 'regular'}_${format(new Date(), 'yyyyMMdd_HHmm')}.pdf`);
};
